### ISSUE TITLE
Slideshow Fun Fact (Fun Page)

### ISSUE THREAD

**Issue by sugianto228** [CherryPhil/iDiet#17]
As an inexperienced person, I want to learn more about dieting in a fun and engaging way so that I can start  committing to my diet and hopefully become a healthy person.

**Comment by CherryPhil** [comment]
1. Slideshow function using javascript with overlay text about fun facts, motivational text and other useful information about starting a diet.
2. Set interval function to change slides periodically, so that users will see different content most of the time.
